import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from 'sonner'

import "./globals.css";
import "../global/styles/main.scss";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/effect-fade";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Toaster closeButton richColors position="top-right"  expand={false} />
        {children}
      </body>
    </html>
  );
}
